### ISSUE TITLE
Иногда ставится обложка от предыдущего трека

### ISSUE THREAD

**Issue by OctoNezd** [OctoNezd/vkmus#1]
![image](https://cloud.githubusercontent.com/assets/15308404/26529858/33c7e918-43d1-11e7-8f0d-c091516a9c4e.png)

**Comment by OctoNezd** [comment]
Это можно починить (предполагаю) убрав поточность у создания трека, но это повысит время переключения трека.

Также, можно ставить что-то в Queue, и проверять какой нибудь id.

**Comment by OctoNezd** [comment]
Убирание поточности не помогает.

**Comment by OctoNezd** [comment]
Фикс сломал все. Мило.

**Comment by bouncepaw** [comment]
@OctoNezd :(

**Comment by bouncepaw** [comment]
@bouncepaw ЧООО КРУТО КАК ЭТО РАБОТАЕТ

**Comment by OctoNezd** [comment]
Починировано https://github.com/OctoNezd/vkmus/commit/a8d185526df612a73db4dd1b119567b9b04c482a
