### ISSUE TITLE
Qt Windows Plugin

### ISSUE THREAD

**Issue by mrsteyk** [OctoNezd/vkmus#11]
# Окто ты дебил. 
![image](https://cloud.githubusercontent.com/assets/10615163/26752166/4fa8f7bc-4863-11e7-8274-2991c2ea4ddd.png)

> Что за хуйня. Фикси быстро! 

@OctoNezd

**Comment by mrsteyk** [comment]
![image](https://cloud.githubusercontent.com/assets/10615163/26752176/825e7632-4863-11e7-960a-1ed04eb303f3.png)
Даже со всеми возможными длл.

**Comment by mrsteyk** [comment]
![image](https://cloud.githubusercontent.com/assets/10615163/26752179/91550d90-4863-11e7-9af9-fef19f4bcaa6.png)
Даже со все-возможными длл

**Comment by OctoNezd** [comment]
Я хз че это. На вроде вроде пукте надо ставить с сайта разработчика

**Comment by OctoNezd** [comment]
На винде*

**Comment by mrsteyk** [comment]
@OctoNezd [https://www.riverbankcomputing.com/software/pyqt/download5](https://www.riverbankcomputing.com/software/pyqt/download5)

> Binary Packages
> Wheels are provided for Python v3.5 and later for 64-bit Linux, OS X and 32-bit and 64-bit Windows. These include everything needed for PyQt5 development except for Python itself.
> So long as you are using a supported version of Python you can install PyQt5 from PyPi by running: 
>     pip3 install PyQt5

**Comment by OctoNezd** [comment]
Да, это

**Comment by OctoNezd** [comment]
Мистика. Я уверен тут виновата винда

**Comment by mrsteyk** [comment]
Тут виноват ты  _)

**Comment by mrsteyk** [comment]
Тебе говорили!
Тебя пердупреждали!!!

**Comment by OctoNezd** [comment]
Нет блять, это pygs(но это не точно)

**Comment by mrsteyk** [comment]
ОРИЕНТИРОВАН НА РАШКУ
@ 
ЮЗАЕТ Qt В КОТОРОЙ ДЕПЛОИНГ ПОД ВИНДУ - АД
@ 
ВК
@ 
ПОЧТИ ВСЕ ПОЛЬЗОВАТЕЛИ ВК И ЕЁ МУЗЫКИ - НЕ ДЕВЕЛОПЕРЫ
@ 
ДЛЯ РАБОТЫ НУЖНО СКАЧАТЬ Qt  С КОМПИЛЯТОРОМ
@ 
Nuff said
@ 
It goes on and on...

**Comment by OctoNezd** [comment]
https://stackoverflow.com/questions/20495620/qt-5-1-1-application-failed-to-start-because-platform-plugin-windows-is-missi

**Comment by mrsteyk** [comment]
@OctoNezd про pygs  я вообще молчу, там нужен vc++ buid tools

**Comment by OctoNezd** [comment]
Под винду есть меридиан, во. А под линь VKMus

**Comment by foxpy** [comment]
@mrsteyk:

> В КОТОРОЙ ДЕПЛОИНГ ПОД ВИНДУ - АД

Ради такого можно и виртуалку с линуксом накатить. А еще в вк зарегаться.

**Comment by ctl** [comment]
@OctoNezd Зачем вообще эти плееры? Можно просто скачать свой плейлист в вк и слушать в любимом плеере. А еще есть вариант получше : всякие сервисы типа Spotify !

**Comment by sojalei** [comment]
@ctl Треков моего любимого исполнителя нет в спотифи. Такие дела

**Comment by ctl** [comment]
@sojalei Вариантов кроме спотифи ещё достаточно

**Comment by sojalei** [comment]
@OctoNezd как вариант сделай скрипт для скачивания музла с вк без всего лишнего.

**Comment by OctoNezd** [comment]
Для скачивания - vk2pls.

**Comment by sojalei** [comment]
@OctoNezd Баги в нём

**Comment by mrsteyk** [comment]
Та хуйита на которую ты меня направил не помогла. И Окто, надень очки!

**Comment by mrsteyk** [comment]
libEGL присутсвует

**Comment by ctl** [comment]
@mrsteyk Решение :
Установи Manjaro на компьютер с характеристиками как у Окто и запускай оттуда

**Comment by OctoNezd** [comment]
@mrsteyk, у тебя часом питон не через мингв стоит?

**Comment by mrsteyk** [comment]
@OctoNezd я что дебил?

**Comment by OctoNezd** [comment]
@mrsteyk да

**Comment by mrsteyk** [comment]
@ctl nice try. Но у него антегрос и я запускаю на точно такой же печке только на винде.

**Comment by ctl** [comment]
@mrsteyk Так поставь антегрос

**Comment by OctoNezd** [comment]
Я считаю что у тебя PyQt5 как-то криво стоит.

**Comment by mrsteyk** [comment]
@OctoNezd как я мог его криво поставить?

**Comment by mrsteyk** [comment]
@ctl ахахахахахах. Печка не моя и особо шаманить я не могу - очень заметно.

**Comment by mrsteyk** [comment]
Решилось кривой установкой пакета с sourceforge!

**Comment by OctoNezd** [comment]
А Я ГРИЛ!

**Comment by mrsteyk** [comment]
Нет не решилось

**Comment by OctoNezd** [comment]
@mrsteyk кек

**Comment by mrsteyk** [comment]
@OctoNezd Я пошаманил и пришел к выводу, что Окто дебил.
И создатель PyQt5 тоже.

**Comment by OctoNezd** [comment]
@mrsteyk Understandable, have a nice day

**Comment by mrsteyk** [comment]
@OctoNezd Have a nice importable dll. Cuz it cant import fooqin dll and find fucntions.
