### ISSUE TITLE
BUGS

### ISSUE THREAD

**Issue by sojalei** [OctoNezd/vkmus#2]
При прослушивании некоторых треков звук не появляется пока не нажмёшь на ползунок, на других треках зацикливается первые звуки и так до конца - исправляется тем же методом

UPD: Хочется отметить, что эти баги появляются всегда на определённых треках. И О ЧУДО! Треки с одного и того же альбома.

**Comment by OctoNezd** [comment]
Про второе я знаю, баг явно связан с QMediaPlayer, надо бы найти другой источник звука. Про первое - не знаю, опять же наверное QMediaPlayer, паскуда такая.

**Comment by sojalei** [comment]
@OctoNezd в pygame таких проблем не наблюдается

**Comment by OctoNezd** [comment]
Проблема в том, что сейчас некоторые функции крупно сидят на ~~игле~~ сигналах QMediaPlayer. Можешь кинуть пример по проигрыванию и получению данных с pygame? Придется опять заниматься половыми актами с тредингом, но мне не привыкать

**Comment by OctoNezd** [comment]
По поводу pygame:`Be aware that MP3 support is limited. On some systems an unsupported format can crash the program, e.g. Debian Linux. Consider using OGG instead.`

**Comment by OctoNezd** [comment]
Вот что нашел: https://wiki.videolan.org/Python_bindings . Думаю если сделаю на этом, проблем не будет точно. Но это не точно

**Comment by OctoNezd** [comment]
Сделал фикс, он не очень, запускает проигрывание всегда с 900 милисекунды, но работает отлично, разницы не слышно
